name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mysql_db:
        image: mysql:5.7
        env:
          MYSQL_ROOT_HOST: "%"
          MYSQL_ROOT_PASSWORD: fynd123
          MYSQL_DATABASE: fynd_acad
          MYSQL_USER: fynd_acad
          MYSQL_PASSWORD: fynd123
        ports:
          - "3305:3306"
        volumes:
          - /home/nitin/fynd_acad/docker-data-imdb4:/var/lib/mysql

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Wait for MySQL to be ready
      run: |
        timeout=60
        while ! nc -z localhost 3305 && [ $timeout -gt 0 ]; do
          sleep 1
          timeout=$((timeout-1))
        done
        if [ $timeout -eq 0 ]; then
          echo "MySQL not ready within the timeout."
          exit 1
        fi

    - name: Run tests inside the test container
      run: docker-compose run test pytest
