name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mysql_db:
        image: mysql:5.7
        container_name: mysql_db
        hostname: mysql_db
        environment:
          - MYSQL_ROOT_HOST="%"
          - MYSQL_ROOT_PASSWORD=fynd123
          - MYSQL_DATABASE=fynd_acad
          - MYSQL_USER=fynd_acad
          - MYSQL_PASSWORD=fynd123 
        ports:
          - "3305:3306"
        volumes:
          - /home/nitin/fynd_acad/docker-data-imdb4:/var/lib/mysql 

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run tests inside the app container
      run: docker-compose exec app pytest
