name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Start app container
        run: docker-compose up -d


      - name: Run tests in test container
        run: sh tests.sh

      - name: Upload test results (if tests run)
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: test-results/

